# Generated by Django 4.2.1 on 2023-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("image_url", models.URLField()),
                ("text", models.TextField()),
                ("date", models.TextField()),
                ("time", models.TextField()),
                ("read_more_url", models.URLField()),
            ],
        ),
    ]
